site_name: 花曜之境伺服器Wiki
site_url: https://wiki.bloomcraft.xyz
site_description: 在花曜之境中創造屬於你的傳奇故事
theme:
  name: material
  custom_dir: overrides
  logo: images/favicon.png
  favicon: images/favicon.png
  font: false # 我們自己帶字體
  features:
    - navigation.tabs
    - navigation.top
  palette:
    scheme: slate # 官方內建的暗色系
    primary: pink
    accent: pink
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true  
plugins:
  - social:
      cards: true
      cards_layout_options:
        font_family: "Noto Sans TC"
      cards_color:
        fill: "#0a0e1a"
        text: "#ffffff"
      cards_dir: assets/images/social
